// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5XW6lKNJ0B7-2W2_4yw7_-PnrEr4FZ9o',
    appId: '1:657851768701:web:bb3a490888d70ddd6af614',
    messagingSenderId: '657851768701',
    projectId: 'eventosepis-8edf0',
    authDomain: 'eventosepis-8edf0.firebaseapp.com',
    storageBucket: 'eventosepis-8edf0.firebasestorage.app',
    measurementId: 'G-K1PVK125DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfsyDbsiodgx3PnN1xGYOxJO8a5ZR2sbo',
    appId: '1:657851768701:android:a728c7b38c8b68d56af614',
    messagingSenderId: '657851768701',
    projectId: 'eventosepis-8edf0',
    storageBucket: 'eventosepis-8edf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5bbtzVCRBueWE-YGTQ6BxXaYxOr5_0M',
    appId: '1:277557539813:ios:85e272f79c7a6b0ef0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
    iosClientId: '277557539813-l91ciljkerg2s93h2v7kpc9io1rq4nsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5bbtzVCRBueWE-YGTQ6BxXaYxOr5_0M',
    appId: '1:277557539813:ios:85e272f79c7a6b0ef0750c',
    messagingSenderId: '277557539813',
    projectId: 'eventos-e7a2c',
    storageBucket: 'eventos-e7a2c.firebasestorage.app',
    iosClientId: '277557539813-l91ciljkerg2s93h2v7kpc9io1rq4nsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5XW6lKNJ0B7-2W2_4yw7_-PnrEr4FZ9o',
    appId: '1:657851768701:web:4aa390e514e0dedb6af614',
    messagingSenderId: '657851768701',
    projectId: 'eventosepis-8edf0',
    authDomain: 'eventosepis-8edf0.firebaseapp.com',
    storageBucket: 'eventosepis-8edf0.firebasestorage.app',
    measurementId: 'G-JND4N72BJN',
  );

}